config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :establishments, except: [:show, :index]
  resources :companies, except: [:show, :index]
  resources :admins, except: [:show, :index]

  get 'companies/index'
  get 'companies/sign_in'
  get 'companies/sign_up'
  post 'companies/register'
  post 'companies/log_in'
  get 'companies/log_out'
  get 'companies/containers'
  get 'companies/request_container'
  get 'companies/request_container_choose_establishment'
  get 'companies/request_container_last_step'
  get 'companies/update_state_container'
  get 'companies/configuration'
  get 'companies/drop_out'
  post 'companies/edit_data'
  post 'companies/edit_password'
  post 'companies/modify_data'

  get 'establishments/index'
  get 'establishments/sign_in'
  get 'establishments/sign_up'
  post 'establishments/register'
  post 'establishments/log_in'
  get 'establishments/log_out'
  get 'establishments/drop_out'
  get 'establishments/containers'
  get 'establishments/accept_container_request'
  get 'establishments/configuration'
  post 'establishments/edit_data'
  post 'establishments/edit_password'
  get 'establishments/update_state_container'
  post 'establishments/delete_container'

  get 'admins/index'
  get 'admins/sign_in'
  get 'admins/sign_up'
  post 'admins/log_in'
  get 'admins/log_out'
  get 'admins/new_company'
  post 'admins/accept_company'
  get 'admins/new_establishment'
  post 'admins/accept_establishment'
  get 'admins/change_request'
  post 'admins/accept_change_request'

end

app/views/admins/change_request.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/admins/index"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%#= link_to "Perfil", companies_index_path %></li>
      <li><%#= link_to "Contenedores", companies_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @change["current_admin"]["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%#= link_to "Configuración", companies_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Cerrar sesión", admins_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<% if flash[:update_accept] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-info">
          <a class="close" data-dismiss="alert">&times;</a>
          <!--<strong>Aviso</strong>--> <%= flash[:update_accept] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<br>

<div class="container">
  <div class="row">
    <div class="col-md-12">

    <h1 align="center">Validación Cambios de datos de Compañias</h1>
    </div>
  </div>
  <hr>

  <div class="row">

    <!--left col-->
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">Listados de Peticiones de Cambio</div>
        

          <div class="table-responsive">
            <table class="table table-bordered">
                <thead>
                    <tr>
                        <th>#</th>
                        <th>Nombre(Actual)</th>
                        <th>Nombre(Nuevo)</th>
                        <th>Email(Actual)</th>
                        <th>Email(Nuevo)</th>
                        <th>Direccion(Actual)</th>
                        <th>Direccion(Nueva)</th>
                        <th></th>

                    </tr>
                </thead>
                <tbody>

                  <%@change["change"].each_with_index do |chan,index|%>
                  
                    <tr>
                        <td><%= index+1 %></td>
                        <td><%= @change["comp"][index]["name"]%></td>
                        <td><%= chan["name"]%></td>
                        <td><%= @change["comp"][index]["email"]%></td>
                        <td><%= chan["email"]%></td>
                        <td><%= @change["comp"][index]["address"]%></td>
                        <td><%= chan["address"]%></td>
                        <td><%= link_to 'Aceptar', admins_accept_change_request_path(:change_id => chan["id"]), :data => {:confirm => '¿Está seguro que desea actualizar este registro?'}, :class => "btn btn-success btn-md", method: :post %></td>

                    </tr>

                  <%end%>
                </tbody>
            </table>
          </div>
        </div>
      </div>
      
    </div>
  
    <div class="col-sm-2 col-sm-offset-10"><%= link_to "Inicio", admins_index_path, class: "  btn btn-default btn-lg btn-block" %>
    </div>
  </div>

app/views/admins/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/admins/index"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%#= link_to "Perfil", companies_index_path %></li>
      <li><%#= link_to "Contenedores", companies_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @admin["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%#= link_to "Configuración", companies_configuration_path %></li>
          <li><%= link_to "Cerrar sesión", admins_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>


<div class="container">
  <div class="row">
    <div class="col-md-12">

    <h1 align="center">Panel Administrativo</h1>
    </div>
  </div>
  <hr>

  <div class="row">

    <!--left col-->
    <div class="col-md-offset-4 col-md-4">
      <%= link_to "Administrar Compañias", admins_new_company_path,:class=>"btn btn-success btn-lg btn-block"%>
    </div>

    
  </div>
  <br>
  <div class="row">

    <!--left col-->
    <div class="col-md-offset-4 col-md-4">
      <%= link_to "Administrar Instituciones", admins_new_establishment_path,:class=>"btn btn-success btn-lg btn-block"%>
    </div>

    
  </div>
  <br>
  <div class="row">

    <!--left col-->
    <div class="col-md-offset-4 col-md-4">
      <%= link_to "Validar Cambios en Compañias", admins_change_request_path,:class=>"btn btn-success btn-lg btn-block"%>
    </div>

    
  </div>

</div>

app/views/admins/new_company.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/admins/index"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%#= link_to "Perfil", companies_index_path %></li>
      <li><%#= link_to "Contenedores", companies_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @comps["current_admin"]["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%#= link_to "Configuración", companies_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Log out", admins_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
<% if flash[:company_accept] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-info">
          <a class="close" data-dismiss="alert">&times;</a>
          <!--<strong>Aviso</strong>--> <%= flash[:company_accept] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<br>

<div class="container">
  <div class="row">
    <div class="col-md-12">

    <h1 align="center">Validación de Nuevas Compañias</h1>
    </div>
  </div>
  <hr>

  <div class="row">

    <!--left col-->
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">Listados de Compañias no validadas</div>
        

      <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Direccion</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

              <%@comps["comps"].each_with_index do |comp,index|%>
              
                <tr>
                    <td><%= index+1 %></td>
                    <td><%= comp["name"]%></td>
                    <td><%= comp["email"]%></td>
                    <td><%= comp["address"]%></td>
                    <td><%= link_to 'Aceptar', admins_accept_company_path(:comp_id => comp["id"]), :data => {:confirm => '¿Está seguro que desea aceptar esta empresa?'}, :class => "btn btn-success btn-md", method: :post %></td>
                    <td></td>
                </tr>

              <%end%>
            </tbody>
        </table>
    </div>
  </div>




    </div>

    
  </div>
    <div class="col-sm-2 col-sm-offset-10"><%= link_to "Inicio", admins_index_path, class: "  btn btn-default btn-lg btn-block" %>
    </div>

</div>

app/views/admins/new_establishment.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/admins/index"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%#= link_to "Perfil", companies_index_path %></li>
      <li><%#= link_to "Contenedores", companies_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @ests["current_admin"]["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%#= link_to "Configuración", companies_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Log out", admins_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>
<% if flash[:establishment_accept] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-info">
          <a class="close" data-dismiss="alert">&times;</a>
          <!--<strong>Aviso</strong>--> <%= flash[:establishment_accept] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<br>


<div class="container">
  <div class="row">
    <div class="col-md-12">

    <h1 align="center">Validación de Nuevas Instituciones</h1>
    </div>
  </div>
  <hr>

  <div class="row">

    <!--left col-->
    <div class="col-md-12">
      <div class="panel panel-default">
        <div class="panel-heading">Listados de Instituciones no validadas</div>
        

      <div class="table-responsive">
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>#</th>
                    <th>Nombre</th>
                    <th>Email</th>
                    <th>Direccion</th>
                    <th></th>
                    <th></th>
                </tr>
            </thead>
            <tbody>

              <%@ests["ests"].each_with_index do |est,index|%>
              
                <tr>
                    <td><%= index+1 %></td>
                    <td><%= est["name"]%></td>
                    <td><%= est["email"]%></td>
                    <td><%= est["address"]%></td>
                    <td><%= link_to 'Aceptar', admins_accept_establishment_path(:est_id => est["id"]), :data => {:confirm => '¿Está seguro que desea aceptar esta institución?'}, :class => "btn btn-success btn-md", method: :post %></td>
                    <td></td>
                </tr>

              <%end%>
            </tbody>
        </table>
    </div>
  </div>




    </div>

    
  </div>
  <div class="col-sm-2 col-sm-offset-10"><%= link_to "Inicio", admins_index_path, class: "  btn btn-default btn-lg btn-block" %>
  </div>  

</div>

app/views/admins/sign_in.html.erb
  <nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/">Inicio</a></li>
    </ul>
  </div>
</nav>

<% if flash[:wrong_credentials] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-danger">
          <a class="close" data-dismiss="alert">&times;</a>
          <strong>¡Error!</strong> <%= flash[:wrong_credentials] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<div>
<br><br><br><br>
  <h1 align="center">Login de Administrador</h1>
</div>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= form_tag controller: "admins", action: "log_in", method: "post", :class => "form-signin" do %>
      <div class="form-group">
        <%= text_field_tag :email, '', class: "form-control", placeholder: "Email" %>
      </div>
      <div class="form-group">
        <%= password_field_tag :password, '', class: "form-control", placeholder: "Password" %>
      </div>

      <%= submit_tag "Iniciar Sesión", class: "btn btn-success btn-lg btn-block" %>
    <% end %>
    <hr>
    
  </div>
  <div class="col-md-5"></div>
</div>