config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :establishments, except: [:show, :index]
  resources :companies, except: [:show, :index]
  resources :admins, except: [:show, :index]

  get 'companies/index'
  get 'companies/sign_in'
  get 'companies/sign_up'
  post 'companies/register'
  post 'companies/log_in'
  get 'companies/log_out'
  get 'companies/containers'
  get 'companies/request_container'
  get 'companies/request_container_choose_establishment'
  get 'companies/request_container_last_step'
  get 'companies/update_state_container'
  get 'companies/configuration'
  get 'companies/drop_out'
  post 'companies/edit_data'
  post 'companies/edit_password'
  post 'companies/modify_data'

  get 'establishments/index'
  get 'establishments/sign_in'
  get 'establishments/sign_up'
  post 'establishments/register'
  post 'establishments/log_in'
  get 'establishments/log_out'
  get 'establishments/drop_out'
  get 'establishments/containers'
  get 'establishments/accept_container_request'
  get 'establishments/configuration'
  post 'establishments/edit_data'
  post 'establishments/edit_password'
  get 'establishments/update_state_container'
  post 'establishments/delete_container'

  get 'admins/index'
  get 'admins/sign_in'
  get 'admins/sign_up'
  post 'admins/log_in'
  get 'admins/log_out'
  get 'admins/new_company'
  post 'admins/accept_company'
  get 'admins/new_establishment'
  post 'admins/accept_establishment'
  get 'admins/change_request'
  post 'admins/accept_change_request'

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand container-fluid" href="/"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Regístrate como empresa", companies_sign_up_path %></li>
      <li><%= link_to "Regístrate como institución", establishments_sign_up_path %></li>
    </ul>
  </div>
</nav>
<% if flash[:comp_notice] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-info">
          <a class="close" data-dismiss="alert">&times;</a>
          <!--<strong>Aviso</strong>--> <%= flash[:comp_notice] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<% if flash[:adm_notice] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-info">
          <a class="close" data-dismiss="alert">&times;</a>
          <!--<strong>Aviso</strong>--> <%= flash[:adm_notice] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<% if flash[:est_notice] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-info">
          <a class="close" data-dismiss="alert">&times;</a>
          <!--<strong>Aviso</strong>--> <%= flash[:est_notice] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<% if flash[:establishment_validate] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-success">
          <a class="close" data-dismiss="alert">&times;</a>
          <!--<strong>Aviso</strong>--> <%= flash[:establishment_validate] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<% if flash[:company_validate] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-success">
          <a class="close" data-dismiss="alert">&times;</a>
          <!--<strong>Aviso</strong>--> <%= flash[:company_validate] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<% if flash[:dropout] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-success">
          <a class="close" data-dismiss="alert">&times;</a>
          <!--<strong>Aviso</strong>--> <%= flash[:dropout] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>

<br><br><br>
<div class="container-full">
  <div class="row">
    <div class="col-lg-12 text-center v-center">

      <h1>Bienvenidos a <%=image_tag("brand_blanco.png", :alt => "R-cyclo", :title => "R-cyclo", width: "300") %></h1>
      <p class="lead">Reduce, Reusa, Recicla</p>

      <br>

      <div class="container-fluid">
        <div class="row">
          <div class="col-md-4"></div>
          <div class="col-md-2"><%= link_to "Empresa", companies_sign_in_path, class: "	btn btn-success btn-lg btn-block" %></div>
          <div class="col-md-2"><%= link_to "Institución", establishments_sign_in_path, class: "btn btn-success btn-lg btn-block" %></div>
          <div class="col-md-4"></div>
        </div>
      </div>
    </div>

  </div>

  <div class="row">
    <div class="col-lg-12 text-center v-center" style="font-size:39pt;">
      <a href="#"><i class="icon-google-plus"></i></a> <a href="#"><i class="icon-facebook"></i></a>  <a href="#"><i class="icon-twitter"></i></a> <a href="#"><i class="icon-github"></i></a> <a href="#"><i class="icon-pinterest"></i></a>
    </div>
  </div>

  <br><br><br><br><br>

</div>

<div class="container">

  <h2>Empresas</h2>

  <hr>

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Ayuda a instituciones que reciclan</h3></div>
        <div class="panel-body">Registrándote en nuestro sitio, das la posibilidad de ofrecer tus desechos reciclables a instituciones que los recolecta para financiar actividades o conseguir recursos valiosos por dicho material.
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>¿Contenedor lleno? ¡Notifícalo!</h3></div>
        <div class="panel-body">Puedes avisar a la institución asociada, con un sólo click, si tu contenedor ya está listo para ser retirado.
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Solicita tu contenedor</h3></div>
        <div class="panel-body">¿Ya sabes a qué institución ayudarás? Pídeles un contenedor de desechos reciclables. Periódicamente, ellos irán a tu empresa a retirarlo.
        </div>
      </div>
    </div>
  </div>

  <h2>Instituciones</h2>

  <hr>

  <div class="row">
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>¡Retira los contenedores!</h3></div>
        <div class="panel-body">Una vez que ya tengas definida una ruta, podrás ver en línea, a través de la aplicación en tu celular, la ubicación de todos los contenedores a retirar. Además, si un contenedor se llena cerca de donde estés, se notificará en el mapa de tu sesión.
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Checkea los contenedores listos para retirar</h3></div>
        <div class="panel-body">Tendrás a disposición un mapa que mostrará la ubicación de todos tus contenedores, en donde podrás ver si está vacío, en uso o lleno.
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-heading"><h3>Potencia tu campaña</h3></div>
        <div class="panel-body">¿Necesitas recolectar material desechable, y estás iniciando una campaña de acopio? Acá podrás encontrar empresas dispuestas a darte una mano.
        </div>
      </div>
    </div>
  </div>

</div>