config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :establishments, except: [:show, :index]
  resources :companies, except: [:show, :index]
  resources :admins, except: [:show, :index]

  get 'companies/index'
  get 'companies/sign_in'
  get 'companies/sign_up'
  post 'companies/register'
  post 'companies/log_in'
  get 'companies/log_out'
  get 'companies/containers'
  get 'companies/request_container'
  get 'companies/request_container_choose_establishment'
  get 'companies/request_container_last_step'
  get 'companies/update_state_container'
  get 'companies/configuration'
  get 'companies/drop_out'
  post 'companies/edit_data'
  post 'companies/edit_password'
  post 'companies/modify_data'

  get 'establishments/index'
  get 'establishments/sign_in'
  get 'establishments/sign_up'
  post 'establishments/register'
  post 'establishments/log_in'
  get 'establishments/log_out'
  get 'establishments/drop_out'
  get 'establishments/containers'
  get 'establishments/accept_container_request'
  get 'establishments/configuration'
  post 'establishments/edit_data'
  post 'establishments/edit_password'
  get 'establishments/update_state_container'
  post 'establishments/delete_container'

  get 'admins/index'
  get 'admins/sign_in'
  get 'admins/sign_up'
  post 'admins/log_in'
  get 'admins/log_out'
  get 'admins/new_company'
  post 'admins/accept_company'
  get 'admins/new_establishment'
  post 'admins/accept_establishment'
  get 'admins/change_request'
  post 'admins/accept_change_request'

end

app/controllers/companies_controller.rb
require 'httparty'
require 'json'

class CompaniesController < ApplicationController
  before_action :not_erased_company_only, except: [:sign_in, :log_in, :sign_up, :register]
  before_action :active_company_only, except: [:sign_in, :log_in, :sign_up, :register]

  def active_company_only
    if defined? @@access_token and defined? @@client and defined? @@uid
      company_signed_in = HTTParty.get('https://api-rcyclo.herokuapp.com/companies/signed_in', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
    end

    if company_signed_in.nil? or company_signed_in["active"] == false
      redirect_to root_path
    end
  end

  def sign_in
  end

  def sign_up
  end

  def register
    result_register = HTTParty.post('https://api-rcyclo.herokuapp.com/companies/new', :body => {:name => params[:name], :address => params[:address], :email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation]}.to_json, :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    flash[:company_validate] = "Solicitud enviada. Espere la validación de administración vía email."
    redirect_to controller: 'welcome', action: 'index'
  end

  def log_in
    email = params[:email]
    password = params[:password]

    result_log_in = HTTParty.post('https://api-rcyclo.herokuapp.com/company_auth/sign_in', :body => {:email => email, :password => password}.to_json, :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    case result_log_in.code
      when 200
        @@uid = result_log_in.headers["uid"]
        @@client = result_log_in.headers["client"]
        @@access_token = result_log_in.headers["access-token"]

        redirect_to :action => 'index'
      else
        flash[:wrong_credentials] = "Combinación de Email y Password Errónea"

        redirect_to action: 'sign_in'
    end
  end

  def log_out
    HTTParty.delete('https://api-rcyclo.herokuapp.com/company_auth/sign_out', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    @@access_token = nil
    @@client = nil
    @@uid = nil

    flash[:comp_notice] = "Desconectado con éxito"
    redirect_to controller: 'welcome', action: 'index'
  end

  def index
    @company = HTTParty.get('https://api-rcyclo.herokuapp.com/companies/index', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
    @data = HTTParty.get('https://api-rcyclo.herokuapp.com/companies/containers', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
  end

  def new
  end

  def create
  end

  def update
  end

  def edit_data
    company_edit = HTTParty.post('https://api-rcyclo.herokuapp.com/companies/modify_data', :body => {:name => params[:name], :email => params[:email], :address => params[:address]}.to_json, :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    case company_edit.code
      when 200
        flash[:updated_data_succes] = "Los datos fueron enviados para su aprobación."
      else
        flash[:updated_data_failure] = "Hubo un error en el envío de sus datos."
      end

      redirect_to :action => 'configuration'
  end

  def edit_password
    company_edit_password = HTTParty.put('https://api-rcyclo.herokuapp.com/company_auth/', :body => {:password => params[:password], :password_confirmation => params[:password_confirmation]}.to_json, :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    case company_edit_password.code
      when 200
        flash[:updated_pass_succes] = "La contraseña fue actualizada."
      else
        flash[:updated_pass_failure] = "Hubo un error en la actualización de su contraseña."
      end

      redirect_to :action => 'configuration'
  end

  def destroy
  end

  def show
  end

  def containers
    @data = HTTParty.get('https://api-rcyclo.herokuapp.com/companies/containers', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
  end

  def request_container
    @data = HTTParty.get('https://api-rcyclo.herokuapp.com/companies/waste_types_all', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
  end

  def request_container_choose_establishment
    @data = HTTParty.get('https://api-rcyclo.herokuapp.com/companies/establishments_by_waste_type', :body => {:waste_type_id => params[:waste_type_id]}.to_json, :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
  end

  def request_container_last_step
    HTTParty.get('https://api-rcyclo.herokuapp.com/companies/create_container_by_company_request', :body => {:establishment_id => params[:establishment_id], :waste_type_id => params[:waste_type_id]}.to_json, :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    flash[:success] = "Contenedor solicitado. Espere confirmación de la institución."
    redirect_to action: 'containers'
  end

  def update_state_container
    HTTParty.get('https://api-rcyclo.herokuapp.com/companies/update_state_container', :body => {:container_id => params[:container_id], :status_id => params[:status_id]}.to_json, :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    redirect_to action: 'containers'
  end

  def configuration
    @company = HTTParty.get('https://api-rcyclo.herokuapp.com/companies/index', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
  end

  def drop_out
    HTTParty.get('https://api-rcyclo.herokuapp.com/companies/drop_out', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    flash[:dropout] = "Haz sido dado de baja. Para reactivar tu cuenta, inicia sesión."
    redirect_to controller: 'welcome', action: 'index'
  end

  def not_erased_company_only
    if defined? @@access_token and defined? @@client and defined? @@uid
      company_signed_in = HTTParty.get('https://api-rcyclo.herokuapp.com/companies/signed_in', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
    end

    if company_signed_in.nil?
      redirect_to root_path
    else
      if company_signed_in["erased"] == true
        HTTParty.get('https://api-rcyclo.herokuapp.com/companies/return_to_rcyclo', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
      end
    end
  end

  def modify_data

    #result_modify_data = HTTParty.post('https://api-rcyclo.herokuapp.com/companies/modify_data', :body => {:email => email, :password => password}.to_json, :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    result_modify_data = HTTParty.post('https://api-rcyclo.herokuapp.com/companies/modify_data', :body => {"company" =>{:name => params[:name], :address => params[:address], :email=>params[:email]}}.to_json,:headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})


    #result_modify_data = HTTParty.post('https://api-rcyclo.herokuapp.com/companies/modify_data', :body => {:name => params[:name], :address => params[:address], :email=>params[:email]},:headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})


    case result_modify_data.code
      when 200
        @@uid = result_modify_data.headers["uid"]
        @@client = result_modify_data.headers["client"]
        @@access_token = result_modify_data.headers["access-token"]
        flash[:modify_data_success] = "Modificación ingresada. Debe esperar la validación del administrador para la actualización de sus datos."
        redirect_to :action => 'index'


      else
        flash[:modify_data_error] = "Ocurrió un problema con los datos ingresados"

        redirect_to action: 'edit'
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/configuration.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/companies/index"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Perfil", companies_index_path %></li>
      <li><%= link_to "Contenedores", companies_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @company["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Configuración", companies_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Cerrar sesión  ", companies_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <% if flash[:updated_data_succes] %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">&times;</a>
      <strong>¡Éxito!</strong> <%= flash[:updated_data_succes] %>
    </div>
    <% end %>
    <% if flash[:updated_data_failure] %>
    <div class="alert alert-danger">
      <a class="close" data-dismiss="alert">&times;</a>
      <strong>¡Error!</strong> <%= flash[:updated_data_failure] %>
    </div>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">Editar Datos</div>
      <div class="panel-body">
        <%= form_tag controller: "companies", action: "edit_data", method: "post", :class => "form-signin" do %>
        <div class="form-group">
          <label>Nombre</label>
          <%= text_field_tag :name, '', class: "form-control", value: "#{@company["name"]}" %>
        </div>
        <div class="form-group">
          <label>Email</label>
          <%= text_field_tag :email, '', class: "form-control", value: "#{@company["email"]}" %>
        </div>
        <div class="form-group">
          <label>Address</label>
          <%= text_field_tag :address, '', class: "form-control", value: "#{@company["address"]}" %>
        </div>

        <%= submit_tag "Confirmar", class: "btn btn-primary btn-lg btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

<br >

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <% if flash[:updated_pass_succes] %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">&times;</a>
      <strong>¡Éxito!</strong> <%= flash[:updated_pass_succes] %>
    </div>
    <% end %>
    <% if flash[:updated_pass_failure] %>
    <div class="alert alert-danger">
      <a class="close" data-dismiss="alert">&times;</a>
      <strong>¡Error!</strong> <%= flash[:updated_pass_failure] %>
    </div>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">Editar Contraseña</div>
      <div class="panel-body">
        <%= form_tag controller: "companies", action: "edit_password", method: "post", :class => "form-signin" do %>
        <div class="form-group">
          <label>Contraseña</label>
          <%= password_field_tag :password, '', class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Confirmar contraseña</label>
          <%= password_field_tag :password_confirmation, '', class: "form-control" %>
        </div>

        <%= submit_tag "Confirmar", class: "btn btn-primary btn-lg btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

<div class="container">
  <div class="col-lg-4 col-lg-offset-4">
    <%= link_to "Darse de baja", companies_drop_out_path, class: "btn btn-danger btn-lg btn-block", :data => {:confirm => '¿Está seguro que desea dar de baja su empresa?'} %>
  </div>  
</div>

app/views/companies/containers.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/companies/index"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Perfil", companies_index_path %></li>
      <li><%= link_to "Contenedores", companies_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @data["current_company"]["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Configuración", companies_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Cerrar sesión", companies_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<% if flash[:success] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-success">
          <a class="close" data-dismiss="alert">&times;</a>
          <%= flash[:success] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<br><br><br>

<div class="container">
  <h1>Contenedores</h1>
  <div class="col-sm-2 col-sm-offset-10"><%= link_to "Inicio", companies_index_path, class: "  btn btn-default btn-lg btn-block" %></div> <br><br>

  <hr>

  <div class="row">

    <!--left col-->
    <div class="col-sm-3">

      <ul class="list-group">
        <li class="list-group-item text-muted">Resumen</i></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Total</strong></span> <%= @data["containers_empty"] + @data["containers_half"] + @data["containers_full"] %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Llenos</strong></span> <%= @data["containers_full"] %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Medios</strong></span> <%= @data["containers_half"] %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Vacios</strong></span> <%= @data["containers_empty"] %></li>
      </ul>

      <%= link_to "Solicitar un contenedor", companies_request_container_path, class: "	btn btn-success btn-lg btn-block" %>

    </div>

    <div class="col-sm-9">
      <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a href="#home" data-toggle="tab">Activos</a></li>
        <li><a href="#messages" data-toggle="tab">En espera</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="home">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Título</th>
                  <th>Dirección</th>
                  <th>Última modificación</th>
                  <th>Modificar estado</th>
                </tr>
              </thead>
              <% @data["containers"].each_with_index do |cont, index| %>
              <tr>
                <td><%= index + 1 %> </td>
                <td><%= cont["title"] %></td>
                <td><%= cont["address"] %></td>
                <td><%= cont["updated_at"] %></td>
                <td>
                  <div class="dropdown">
                    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                      <% case cont["status_id"] when 1 %> Vacío
                        <% when 2 %> Medio
                        <% when 3 %> Lleno
                      <% end %>
                      <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                      <% unless cont["status_id"] == 1 %>
                        <li><%= link_to "Vacío", companies_update_state_container_path(:container_id => cont["id"], :status_id => 1) %></li>
                      <% end %>
                      <% unless cont["status_id"] == 2 %>
                        <li><%= link_to "Medio", companies_update_state_container_path(:container_id => cont["id"], :status_id => 2) %></li>
                      <% end %>
                      <% unless cont["status_id"] == 3 %>
                        <li><%= link_to "Lleno", companies_update_state_container_path(:container_id => cont["id"], :status_id => 3) %></li>
                      <% end %>
                    </ul>
                  </div>
                </td>
              </tr>
              <% end %>
            </table>
          </div>
        </div>

        <div class="tab-pane" id="messages">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Título</th>
                  <th>Dirección</th>
                  <th>Última modificación</th>
                </tr>
              </thead>
              <% @data["containers_waiting"].each_with_index do |cont, index| %>
              <tr>
                <td><%= index + 1 %> </td>
                <td><%= cont["title"] %></td>
                <td><%= cont["address"] %></td>
                <td><%= cont["updated_at"] %></td>
              </tr>
              <% end %>
            </table>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>

app/views/companies/create.html.erb
<h1>Companies#create</h1>
<p>Find me in app/views/companies/create.html.erb</p>

app/views/companies/destroy.html.erb
<h1>Companies#destroy</h1>
<p>Find me in app/views/companies/destroy.html.erb</p>

app/views/companies/edit.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/companies/index"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Perfil", companies_index_path %></li>
      <li><%= link_to "Contenedores", companies_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @comp["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Configuración", companies_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Log out", companies_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<h2 class="form-signin-heading" align="center">Modificar datos</h2> <br>
<%= @comp[:name] %>
<%= @comp[:name] %>

<div class="container">
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <form class="form-signin" role="form"></form>
    <section id="features">
      
    <%= form_tag controller: "companies", action: "modify_data", method: "post", :class => "form-signin" do %>
    </section>
       <div class="form-group">
        <%= text_field_tag :name, @comp[:name], class: "form-control", placeholder: "Nombre de la Empresa" %>
      </div>
      <div class="form-group">
        <%= text_field_tag :address, @comp[:address], class: "form-control", placeholder: "Dirección" %>
      </div>
      <div class="form-group">
        <%= text_field_tag :email, @comp[:email], class: "form-control", placeholder: "Email" %>
      </div>

      <%= submit_tag "Modificar Datos", class: "btn btn-success btn-lg btn-block" %>
        </div>
      <% end %>


  </div>
</div>

app/views/companies/new.html.erb
<h1>Companies#new</h1>
<p>Find me in app/views/companies/new.html.erb</p>

app/views/companies/request_container.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/companies/index"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Perfil", companies_index_path %></li>
      <li><%= link_to "Contenedores", companies_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @data["current_company"]["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Configuración", companies_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Cerrar sesión", companies_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
  <h1>Tipos de desechos</h1>
    <div class="col-sm-2 col-sm-offset-10"><%= link_to "Cancelar", companies_index_path, class: "  btn btn-default btn-lg btn-block" %></div> <br><br>

  <hr>

  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Nombre</th>
          <th>Solicitar</th>
        </tr>
      </thead>
      <% @data["waste_types"].each_with_index do |wt, index| %>
        <tr>
          <td><%= index + 1 %> </td>
          <td><%= wt["name"] %></td>
          <td><%= link_to "Continuar", companies_request_container_choose_establishment_path(:waste_type_id => wt["id"]) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/companies/request_container_choose_establishment.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/companies/index"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Perfil", companies_index_path %></li>
      <li><%= link_to "Contenedores", companies_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @data["current_company"]["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Configuración", companies_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Cerrar sesión", companies_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<div class="container">
  <h1>Instituciones</h1>
    <div class="col-sm-2 col-sm-offset-8"><%= link_to "Volver", companies_request_container_path, class: "  btn btn-default btn-lg btn-block" %>
    </div> 
    <div class="col-sm-2"><%= link_to "Cancelar", companies_index_path, class: "  btn btn-default btn-lg btn-block" %></div>
    <br><br><br>

  <hr>

  <div class="table-responsive">
    <table class="table table-hover">
      <thead>
        <tr>
          <th>#</th>
          <th>Institución</th>
          <th>Dirección</th>
          <th>Correo</th>
          <th>Solicitar</th>
        </tr>
      </thead>
      <% @data["establishments"].each_with_index do |est, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= est["name"] %></td>
          <td><%= est["address"] %></td>
          <td><%= est["email"] %></td>
          <td><%= link_to "Continuar", companies_request_container_last_step_path(:establishment_id => est["id"], :waste_type_id => @data["waste_type_id"]) %></td>
        </tr>
      <% end %>
    </table>
  </div>
</div>

app/views/companies/show.html.erb
<h1>Companies#show</h1>
<p>Find me in app/views/companies/show.html.erb</p>

app/views/companies/update.html.erb
<h1>Companies#update</h1>
<p>Find me in app/views/companies/update.html.erb</p>