config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :establishments, except: [:show, :index]
  resources :companies, except: [:show, :index]
  resources :admins, except: [:show, :index]

  get 'companies/index'
  get 'companies/sign_in'
  get 'companies/sign_up'
  post 'companies/register'
  post 'companies/log_in'
  get 'companies/log_out'
  get 'companies/containers'
  get 'companies/request_container'
  get 'companies/request_container_choose_establishment'
  get 'companies/request_container_last_step'
  get 'companies/update_state_container'
  get 'companies/configuration'
  get 'companies/drop_out'
  post 'companies/edit_data'
  post 'companies/edit_password'
  post 'companies/modify_data'

  get 'establishments/index'
  get 'establishments/sign_in'
  get 'establishments/sign_up'
  post 'establishments/register'
  post 'establishments/log_in'
  get 'establishments/log_out'
  get 'establishments/drop_out'
  get 'establishments/containers'
  get 'establishments/accept_container_request'
  get 'establishments/configuration'
  post 'establishments/edit_data'
  post 'establishments/edit_password'
  get 'establishments/update_state_container'
  post 'establishments/delete_container'

  get 'admins/index'
  get 'admins/sign_in'
  get 'admins/sign_up'
  post 'admins/log_in'
  get 'admins/log_out'
  get 'admins/new_company'
  post 'admins/accept_company'
  get 'admins/new_establishment'
  post 'admins/accept_establishment'
  get 'admins/change_request'
  post 'admins/accept_change_request'

end

app/controllers/establishments_controller.rb
require 'httparty'
require 'json'

class EstablishmentsController < ApplicationController
  before_action :not_erased_establishment_only, except: [:sign_in, :log_in, :sign_up, :register]
  before_action :active_establishment_only, except: [:sign_in, :log_in, :sign_up, :register]


  def active_establishment_only
    if defined? @@access_token and defined? @@client and defined? @@uid
      establishment_signed_in = HTTParty.get('https://api-rcyclo.herokuapp.com/establishments/signed_in', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
    end

    if establishment_signed_in.nil? or establishment_signed_in["active"] == false
      redirect_to root_path
    end
  end

  def sign_in
  end

  def sign_up
  end

  def register
    result_register = HTTParty.post('https://api-rcyclo.herokuapp.com/establishments/new', :body => {:name => params[:name], :address => params[:address], :email => params[:email], :password => params[:password], :password_confirmation => params[:password_confirmation]}.to_json, :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    flash[:establishment_validate] = "Solicitud enviada. Espere la validación de administración vía email."
    redirect_to controller: 'welcome', action: 'index'
  end

  def log_in
    email = params[:email]
    password = params[:password]

    result_log_in = HTTParty.post('https://api-rcyclo.herokuapp.com/establishment_auth/sign_in', :body => {:email => email, :password => password}.to_json, :headers => { 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    case result_log_in.code
      when 200
        @@uid = result_log_in.headers["uid"]
        @@client = result_log_in.headers["client"]
        @@access_token = result_log_in.headers["access-token"]

        redirect_to :action => 'index'
      else
        flash[:wrong_credentials] = "Mala combinación de email y password."

        redirect_to :action => 'sign_in'
      end
  end

  def log_out
    HTTParty.delete('https://api-rcyclo.herokuapp.com/establishment_auth/sign_out', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    @@access_token = nil
    @@client = nil
    @@uid = nil

    flash[:est_notice] = "Desconectado con éxito"
    redirect_to controller: 'welcome', action: 'index'
  end

  def index
    @establishment = HTTParty.get('https://api-rcyclo.herokuapp.com/establishments/index', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
    puts "ESTABLISHMENT: " + @establishment.to_s
    @data = HTTParty.get('https://api-rcyclo.herokuapp.com/establishments/containers', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
    puts "DATA: " + @data.to_s
  end

  def new
  end

  def create
  end

  def update
  end

  def edit_data
    establishment_edit = HTTParty.post('https://api-rcyclo.herokuapp.com/establishments/update', :body => {:name => params[:name], :email => params[:email], :address => params[:address]}.to_json, :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    case establishment_edit.code
      when 200
        flash[:updated_data_succes] = "Los datos fueron actualizados."
      else
        flash[:updated_data_failure] = "Hubo un error en la actualización de sus datos."
      end

      redirect_to :action => 'configuration'
  end

  def edit_password
    establishment_edit_password = HTTParty.put('https://api-rcyclo.herokuapp.com/establishment_auth/', :body => {:password => params[:password], :password_confirmation => params[:password_confirmation]}.to_json, :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    case establishment_edit_password.code
      when 200
        flash[:updated_pass_succes] = "La contraseña fue actualizada."
      else
        flash[:updated_pass_failure] = "Hubo un error en la actualización de su contraseña."
      end

      redirect_to :action => 'configuration'
  end

  def drop_out
    HTTParty.get('https://api-rcyclo.herokuapp.com/establishments/drop_out', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    flash[:dropout] = "Haz sido dado de baja. Para reactivar tu cuenta, inicia sesión."
    redirect_to controller: 'welcome', action: 'index'
  end

  def destroy
  end

  def show
  end

  def containers
    @data = HTTParty.get('https://api-rcyclo.herokuapp.com/establishments/containers', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    @companies = []
    companies_id = []

    unique_containers = @data["containers"].uniq { |c| c["company_id"] }.each_with_index do |c, index|
      companies_id[index] = c["company_id"]
      @companies[index] = [c["company_id"], c["title"].split(' - ')[-1].split(' | ')[0], 0, 0, 0, 0, c["latitude"], c["longitude"]]
    end

    indice = 0

    @data["containers"].each do |c|
      companies_id.each_with_index do |comp, index|
        if (comp == c["company_id"])
          indice = index  # en index capturo el indice de @companies sobre la que estamos trabajando
        end
      end

        @companies[indice][2] += 1

      if c["status_id"] == 3
        @companies[indice][5] += 1
      end
      if c["status_id"] == 2
        @companies[indice][4] += 1
      end
      if c["status_id"] == 1
        @companies[indice][3] += 1
      end
    end
  end

  def accept_container_request
    HTTParty.get('https://api-rcyclo.herokuapp.com/establishments/accept_container_request', :body => {:container_id => params[:container_id]}.to_json, :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    flash[:container_succes] = "Contenedor validado exitosamente."
    redirect_to :action => 'containers'
  end

  def configuration
    @establishment = HTTParty.get('https://api-rcyclo.herokuapp.com/establishments/index', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
  end



  def update_state_container
    HTTParty.get('https://api-rcyclo.herokuapp.com/establishments/update_state_container', :body => {:container_id => params[:container_id], :status_id => params[:status_id]}.to_json, :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    redirect_to action: 'containers'
  end

  def delete_container
    result_delete_container = HTTParty.post('https://api-rcyclo.herokuapp.com/establishments/delete_container', :body => {:id_container => params[:id_container]}.to_json,:headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})

    flash[:container_erased] = "Contenedor eliminado."
    redirect_to :action => 'index'
  end

  def not_erased_establishment_only
    if defined? @@access_token and defined? @@client and defined? @@uid
      establishment_signed_in = HTTParty.get('https://api-rcyclo.herokuapp.com/establishments/signed_in', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
    end

    if establishment_signed_in.nil?
      redirect_to root_path
    else
      if establishment_signed_in["erased"] == true
        HTTParty.get('https://api-rcyclo.herokuapp.com/establishments/return_to_rcyclo', :headers => {"access-token" => @@access_token, "client" => @@client, "uid" => @@uid, 'Content-Type' => 'application/json', 'Accept' => 'application/json'})
      end
    end
  end
end

app/helpers/establishments_helper.rb
module EstablishmentsHelper
end

app/views/establishments/configuration.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/establishments/index"><%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Perfil", establishments_index_path %></li>
      <li><%= link_to "Contenedores", establishments_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @establishment["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Configurar datos", establishments_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Cerrar sesión", establishments_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <% if flash[:updated_data_succes] %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">&times;</a>
      <strong>¡Éxito!</strong> <%= flash[:updated_data_succes] %>
    </div>
    <% end %>
    <% if flash[:updated_data_failure] %>
    <div class="alert alert-danger">
      <a class="close" data-dismiss="alert">&times;</a>
      <strong>¡Error!</strong> <%= flash[:updated_data_failure] %>
    </div>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">Editar Datos</div>
      <div class="panel-body">
        <%= form_tag controller: "establishments", action: "edit_data", method: "post", :class => "form-signin" do %>
        <div class="form-group">
          <label>Nombre</label>
          <%= text_field_tag :name, '', class: "form-control", value: "#{@establishment["name"]}" %>
        </div>
        <div class="form-group">
          <label>Email</label>
          <%= text_field_tag :email, '', class: "form-control", value: "#{@establishment["email"]}" %>
        </div>
        <div class="form-group">
          <label>Address</label>
          <%= text_field_tag :address, '', class: "form-control", value: "#{@establishment["address"]}" %>
        </div>

        <%= submit_tag "Confirmar", class: "btn btn-primary btn-lg btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

<br >

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <% if flash[:updated_pass_succes] %>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">&times;</a>
      <strong>¡Éxito!</strong> <%= flash[:updated_pass_succes] %>
    </div>
    <% end %>
    <% if flash[:updated_pass_failure] %>
    <div class="alert alert-danger">
      <a class="close" data-dismiss="alert">&times;</a>
      <strong>¡Error!</strong> <%= flash[:updated_pass_failure] %>
    </div>
    <% end %>
    <div class="panel panel-default">
      <div class="panel-heading">Editar Contraseña</div>
      <div class="panel-body">
        <%= form_tag controller: "establishments", action: "edit_password", method: "post", :class => "form-signin" do %>
        <div class="form-group">
          <label>Contraseña</label>
          <%= password_field_tag :password, '', class: "form-control" %>
        </div>
        <div class="form-group">
          <label>Confirmar contraseña</label>
          <%= password_field_tag :password_confirmation, '', class: "form-control" %>
        </div>

        <%= submit_tag "Confirmar", class: "btn btn-primary btn-lg btn-block" %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>

<div class="container">
  <div class="col-lg-4 col-lg-offset-4">
    <%= link_to "Darse de baja", establishments_drop_out_path, class: "btn btn-danger btn-lg btn-block", :data => {:confirm => '¿Está seguro que desea dar de baja su fundación?'} %>
  </div>
</div>

app/views/establishments/containers.html.erb
<%= @companies %>

<br>
<br>

<%= @data %>

<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/establishments/index"><%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Perfil", establishments_index_path %></li>
      <li><%= link_to "Contenedores", establishments_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @data["current_establishment"]["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Configurar datos", establishments_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Cerrar sesión", establishments_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<style>
  html, body {
    height: 100%;
    margin: 0;
    padding: 0;
  }
  #map {
    height: 100%;
  }
</style>

<div class="col-xs-8 col-xs-offset-2">
  <div id="map-container">
    <div id="map"></div>
  </div>
</div>

<script>
  var map;
  function initMap() {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(function (position) {
        var map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: position.coords.latitude, lng: position.coords.longitude},
          zoom: 8
        })

        // para cada @data["containers"] crear un marcador con su titulo, longitud y latitud

        var companies = <%= raw @companies.to_json %>

        console.log(companies)

        for (i = 0; i < companies.length; i++) {
          var icon;
          if (companies[i][4] >= companies[i][2] * 0.5)
            icon = 'http://maps.google.com/mapfiles/ms/icons/yellow-dot.png'
          else if (companies[i][3] >= companies[i][2] * 0.8)
            icon = 'http://maps.google.com/mapfiles/ms/icons/red-dot.png'
          else
            icon = 'http://maps.google.com/mapfiles/ms/icons/green-dot.png'

          var marker = new google.maps.Marker({
            position: {lat: companies[i][6], lng: companies[i][7]},
            map: map,
            title: companies[i][1],
            icon: icon
          })
        }

        console.log(companies)
      });
    }
  }
</script>

<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBCcnfjpcjMkyHuFtLsfOAsS8jgIPkMzCw&callback=initMap" async defer></script>

<% if flash[:container_succes] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-success">
          <a class="close" data-dismiss="alert">&times;</a>
          <%= flash[:container_succes] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>
<br><br><br>

<div class="container">
  <h1>Contenedores</h1>
  <div class="col-sm-2 col-sm-offset-10"><%= link_to "Inicio", establishments_index_path, class: "btn btn-default btn-lg btn-block" %></div> <br><br>

  <hr>

  <div class="row">

    <!--left col-->
    <div class="col-sm-3">

      <ul class="list-group">
        <li class="list-group-item text-muted">Resumen</i></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Total</strong></span> <%= @data["containers_empty"] + @data["containers_half"] + @data["containers_full"] %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Llenos</strong></span> <%= @data["containers_full"] %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Medios</strong></span> <%= @data["containers_half"] %></li>
        <li class="list-group-item text-right"><span class="pull-left"><strong>Vacios</strong></span> <%= @data["containers_empty"] %></li>
      </ul>

    </div>

    <div class="col-sm-9">
      <ul class="nav nav-tabs" id="myTab">
        <li class="active"><a href="#home" data-toggle="tab">Activos</a></li>
        <li><a href="#messages" data-toggle="tab">Solicitudes</a></li>
      </ul>

      <div class="tab-content">
        <div class="tab-pane active" id="home">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Título</th>
                  <th>Dirección</th>
                  <th>Última modificación</th>
                  <th>Modificar estado</th>
                  <th></th>
                </tr>
              </thead>
              <tbody id="items">
                <% @data["containers"].each_with_index do |cont, index| %>
                <tr>
                  <td><%= index + 1 %> </td>
                  <td><%= cont["title"] %></td>
                  <td><%= cont["address"] %></td>
                  <td><%= cont["updated_at"] %></td>
                  <td>
                    <div class="dropdown">
                      <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <% case cont["status_id"] when 1 %> Vacío
                          <% when 2 %> Medio
                          <% when 3 %> Lleno
                        <% end %>
                        <span class="caret"></span>
                      </button>
                      <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                        <% unless cont["status_id"] == 1 %>
                          <li><%= link_to "Vacío", establishments_update_state_container_path(:container_id => cont["id"], :status_id => 1) %></li>
                        <% end %>
                        <% unless cont["status_id"] == 2 %>
                          <li><%= link_to "Medio", establishments_update_state_container_path(:container_id => cont["id"], :status_id => 2) %></li>
                        <% end %>
                        <% unless cont["status_id"] == 3 %>
                          <li><%= link_to "Lleno", establishments_update_state_container_path(:container_id => cont["id"], :status_id => 3) %></li>
                        <% end %>
                      </ul>
                    </div>
                  </td>
                  <td>
                    <%= link_to 'Eliminar', establishments_delete_container_path(:id_container => cont["id"]), :data => {:confirm => '¿Está seguro que desea eliminar este contenedor?'}, :class => "btn btn-danger btn-sm", method: :post %>
                  </td>
                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>

        <div class="tab-pane" id="messages">
          <div class="table-responsive">
            <table class="table table-hover">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Título</th>
                  <th>Dirección</th>
                  <th>Aceptar solicitud</th>
                </tr>
              </thead>
              <tbody id="items">
                <% @data["containers_request"].each_with_index do |cont, index| %>
                <tr>
                  <td><%= index + 1 %> </td>
                  <td><%= cont["title"] %></td>
                  <td><%= cont["address"] %></td>
                  <td><%= link_to "Aceptar", establishments_accept_container_request_path(:container_id => cont["id"]) %></td>

                </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>

    </div>

  </div>

</div>

app/views/establishments/create.html.erb
<h1>Establishments#create</h1>
<p>Find me in app/views/establishments/create.html.erb</p>

app/views/establishments/destroy.html.erb
<h1>Establishments#destroy</h1>
<p>Find me in app/views/establishments/destroy.html.erb</p>

app/views/establishments/edit.html.erb
<h1>Establishments#edit</h1>
<p>Find me in app/views/establishments/edit.html.erb</p>

app/views/establishments/index.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/establishments/index"><%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-left">
      <li><%= link_to "Perfil", establishments_index_path %></li>
      <li><%= link_to "Contenedores", establishments_containers_path %></li>
    </ul>
    <ul class="nav navbar-nav navbar-right">
      <li><p class="navbar-text">Conectado como <%= @establishment["email"] %></p></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Menú<span class="caret"></span></a>
        <ul class="dropdown-menu" role="menu">
          <li><%= link_to "Configurar datos", establishments_configuration_path %></li>
          <li class="divider"></li>
          <li><%= link_to "Cerrar sesión", establishments_log_out_path %></li>
        </ul>
      </li>
    </ul>
  </div>
</nav>

<% if flash[:container_erased] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-success">
          <a class="close" data-dismiss="alert">&times;</a>
          <%= flash[:container_erased] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end %>

<div class="container">
  <div class="row">

    <!-- main right col -->
    <div class="column col-sm-12" id="main">
      <div class="padding">
        <div class="full col-sm-10">

          <!-- content -->
          <div class="row">

            <!-- main col left -->
            <div class="col-sm-4 col-sm-offset-2">

              <div class="panel panel-default">
                <div class="panel-thumbnail"><img src="http://bligoo.com/media/users/0/38747/images/LOGO%20ORIGINAL_trascender_nuevo.jpg" class="img-responsive"></div>
                <div class="panel-body">
                  <p class="lead"><%= @establishment["name"] %></p>

                  <hr>

                  <p>Ubicación: <%= @establishment["address"] %></p>

                </div>
              </div>


            </div>

            <!-- main col right -->
            <div class="col-sm-6">
              
              <div class="panel panel-default">
                <div class="panel-heading"> <h4>Resumen de contenedores</h4></div>
                <div class="panel-body">
                      <ul class="list-group">
                        <li class="list-group-item text-right"><span class="pull-left"><strong>Total</strong></span> <%= @data["containers_empty"] + @data["containers_half"] + @data["containers_full"] %></li>
                        <li class="list-group-item text-right"><span class="pull-left"><strong>Llenos</strong></span> <%= @data["containers_full"] %></li>
                        <li class="list-group-item text-right"><span class="pull-left"><strong>Medios</strong></span> <%= @data["containers_half"] %></li>
                        <li class="list-group-item text-right"><span class="pull-left"><strong>Vacios</strong></span> <%= @data["containers_empty"] %></li>
                      </ul>
                      <%= link_to "Ver contenedores", establishments_containers_path, class: " btn btn-success btn-lg btn-block" %>
                </div>
              </div>

              

            </div>

          </div>


        </div>
      </div>
    </div>

  </div>
</div>

app/views/establishments/new.html.erb
<h1>Establishments#new</h1>
<p>Find me in app/views/establishments/new.html.erb</p>

app/views/establishments/show.html.erb
<h1>Establishments#show</h1>
<p>Find me in app/views/establishments/show.html.erb</p>

app/views/establishments/sign_in.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
  </div>
  <a class="navbar-brand" href="/"> <%=image_tag("icono.png", :alt => "icono", :title => "Inicio", width: "60") %></a>
  <div class="navbar-collapse collapse">
    <ul class="nav navbar-nav navbar-right">
      <li><a href="/">Inicio</a></li>
    </ul>
  </div>
</nav>

<% if flash[:wrong_credentials] %>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4">
      <div class="alert alert-danger">
          <a class="close" data-dismiss="alert">&times;</a>
          <strong>¡Error!</strong> <%= flash[:wrong_credentials] %>
      </div>
    </div>
    <div class="col-md-4"></div>
  </end>
<% end -%>
<br><br><br><br>
<div class="container">
  <h1 align="center">Inicia sesión como Institución</h1>
</div>

<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4">
    <%= form_tag controller: "establishments", action: "log_in", method: "post", :class => "form-signin" do %>
      <div class="form-group">
        <%= text_field_tag :email, '', class: "form-control", placeholder: "Email" %>
      </div>
      <div class="form-group">
        <%= password_field_tag :password, '', class: "form-control", placeholder: "Contraseña" %>
      </div>

      <%= submit_tag "Iniciar Sesión", class: "btn btn-success btn-lg btn-block" %>
    <% end %>
    <hr>
    <span><%= link_to "Regístrate", establishments_sign_up_path, class: "btn btn-link btn-lg btn-block" %></span>
  </div>
  <div class="col-md-5"></div>
</div>

app/views/establishments/update.html.erb
<h1>Establishments#update</h1>
<p>Find me in app/views/establishments/update.html.erb</p>